name: Build Release

on:
  workflow_dispatch:
    inputs:
      versionName:
        required: true
        description: This releases version name
        default: "1.0.0"
      versionCode:
        required: true
        description: This releases version code
        default: "1000"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Set Version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{github.event.inputs.versionCode}}
          versionName: ${{github.event.inputs.versionName}}

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew packageReleaseUniversalApk

      - name: Store generated APK file
        uses: actions/upload-artifact@v4
        with:
          name: Manager
          path: ./app/build/outputs/apk_from_bundle/release/*.apk
        continue-on-error: true

